### ISSUE TITLE
missing callback ERROR

### ISSUE THREAD

**Issue by rsenthilkumar6** [luisivan/node-picotts#1]
Hi, 

I'm new the to nodejs (javascript) not sure i'm using it correctly. I'm using ubuntu machine and i get the following error.

fs: missing callback Error: ENOENT, unlink '/tmp/0nzw8ajfl102j4i.wav'

and the code which i'm using:

pico.say('Hey this is a test', 'en-US', function() {
    console.log('Cool')
})

**Comment by luisivan** [comment]
Probably something changed in Node random funcs, or you don't have the necessary pico library installed.
This works by generating the audio output to a random file in /tmp using pico, then it reads it back.
